-- Fix usage_logs table schema
ALTER TABLE public.usage_logs 
ADD COLUMN IF NOT EXISTS model_name VARCHAR(100) NOT NULL DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS input_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS output_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS reasoning_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cache_hit_tokens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS multiplier_version VARCHAR(50) NOT NULL DEFAULT 'v3.2',
ADD COLUMN IF NOT EXISTS total_deducted DECIMAL(15, 2) NOT NULL DEFAULT 0;
